DEFAULT_TARGET=app
OBJECTS = main.o MySAG.o

CFLAGS = -g -O3
LDLIBS=
CC=gcc

$(DEFAULT_TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) -o $(DEFAULT_TARGET) $(OBJECTS)

clean:
	rm -f *.o $(DEFAULT_TARGET)

run:	$(DEFAULT_TARGET)
	./$(DEFAULT_TARGET)
